stage('build authenticator and app') {
    node('docker_slave-centos-7.5-x86_64') {
        git([url: 'https://github.com/jacderida/safe_client_libs.git', branch: 'docker_build'])

        def user_id = sh(returnStdout: true, script: 'echo $UID').trim()
        def group_id = sh(returnStdout: true, script: $/eval 'getent group $USER | awk -F : "{ print \$3 }"'/$).trim()
        sh("docker run --name safe_client_libs_real " +
           "-v ${env.WORKSPACE}:/usr/src/crust:Z " +
           "-u ${user_id}:${group_id} " +
           "maidsafe/safe-client-libs-build:0.9.0 scripts/build-real /target")
        sh('mkdir -p target/deploy/real')
        sh('docker cp safe_client_libs_real:/target/release target/deploy/real')
    }
}
