choco install -y 7zip
choco install -y cmake
choco install -y curl
choco install -y dotnet
choco install -y git
choco install -y hashdeep
choco install -y jq
choco install -y llvm
choco install -y microsoft-build-tools
choco install -y mingw
choco install -y ruby
choco install -y visualstudio2017buildtools
choco install -y wget
choco install -y winscp
choco install -y wsl
