C:\ProgramData\chocolatey\choco.exe install -y 7zip
C:\ProgramData\chocolatey\choco.exe install -y cmake
C:\ProgramData\chocolatey\choco.exe install -y curl
C:\ProgramData\chocolatey\choco.exe install -y dotnet
C:\ProgramData\chocolatey\choco.exe install -y git
C:\ProgramData\chocolatey\choco.exe install -y hashdeep
C:\ProgramData\chocolatey\choco.exe install -y jq
C:\ProgramData\chocolatey\choco.exe install -y llvm
C:\ProgramData\chocolatey\choco.exe install -y microsoft-build-tools
C:\ProgramData\chocolatey\choco.exe install -y mingw
C:\ProgramData\chocolatey\choco.exe install -y ruby
C:\ProgramData\chocolatey\choco.exe install -y visualstudio2017buildtools
C:\ProgramData\chocolatey\choco.exe install -y wget
C:\ProgramData\chocolatey\choco.exe install -y winscp
